version: '3.4'
services:
  slack-quiz-bot:
    env_file:
      - config.env
    image: slack-quiz-bot:dev
    container_name: slack-quiz-bot
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/slack-quiz-bot/
